/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeladosRouteImport } from './routes/selados'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ImasRouteImport } from './routes/imas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartasRouteImport } from './routes/cartas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CartaSlugRouteImport } from './routes/carta.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShippingRouteImport } from './routes/admin.shipping'
import { Route as AdminSealedRouteImport } from './routes/admin.sealed'
import { Route as AdminPanelsRouteImport } from './routes/admin.panels'
import { Route as AdminManageCardsRouteImport } from './routes/admin.manage-cards'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsMercadopagoWebhookRouteImport } from './routes/api/public/payments/mercadopago-webhook'
import { Route as ApiPublicMelhorenvioCallbackRouteImport } from './routes/api/public/melhorenvio/callback'
import { Route as ApiPublicHooksUpdatePricesRouteImport } from './routes/api/public/hooks/update-prices'
import { Route as ApiPublicHooksPriceDropCheckRouteImport } from './routes/api/public/hooks/price-drop-check'
import { Route as ApiPublicHooksAutoCancelUnpaidRouteImport } from './routes/api/public/hooks/auto-cancel-unpaid'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeladosRoute = SeladosRouteImport.update({
  id: '/selados',
  path: '/selados',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ImasRoute = ImasRouteImport.update({
  id: '/imas',
  path: '/imas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartasRoute = CartasRouteImport.update({
  id: '/cartas',
  path: '/cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const CartaSlugRoute = CartaSlugRouteImport.update({
  id: '/carta/$slug',
  path: '/carta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSealedRoute = AdminSealedRouteImport.update({
  id: '/sealed',
  path: '/sealed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelsRoute = AdminPanelsRouteImport.update({
  id: '/panels',
  path: '/panels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageCardsRoute = AdminManageCardsRouteImport.update({
  id: '/manage-cards',
  path: '/manage-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMercadopagoWebhookRoute =
  ApiPublicPaymentsMercadopagoWebhookRouteImport.update({
    id: '/api/public/payments/mercadopago-webhook',
    path: '/api/public/payments/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMelhorenvioCallbackRoute =
  ApiPublicMelhorenvioCallbackRouteImport.update({
    id: '/api/public/melhorenvio/callback',
    path: '/api/public/melhorenvio/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUpdatePricesRoute =
  ApiPublicHooksUpdatePricesRouteImport.update({
    id: '/api/public/hooks/update-prices',
    path: '/api/public/hooks/update-prices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPriceDropCheckRoute =
  ApiPublicHooksPriceDropCheckRouteImport.update({
    id: '/api/public/hooks/price-drop-check',
    path: '/api/public/hooks/price-drop-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoCancelUnpaidRoute =
  ApiPublicHooksAutoCancelUnpaidRouteImport.update({
    id: '/api/public/hooks/auto-cancel-unpaid',
    path: '/api/public/hooks/auto-cancel-unpaid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cartas': typeof CartasRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/imas': typeof ImasRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/selados': typeof SeladosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/manage-cards': typeof AdminManageCardsRoute
  '/admin/panels': typeof AdminPanelsRoute
  '/admin/sealed': typeof AdminSealedRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/users': typeof AdminUsersRoute
  '/carta/$slug': typeof CartaSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-cancel-unpaid': typeof ApiPublicHooksAutoCancelUnpaidRoute
  '/api/public/hooks/price-drop-check': typeof ApiPublicHooksPriceDropCheckRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
  '/api/public/melhorenvio/callback': typeof ApiPublicMelhorenvioCallbackRoute
  '/api/public/payments/mercadopago-webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cartas': typeof CartasRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/imas': typeof ImasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/selados': typeof SeladosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/manage-cards': typeof AdminManageCardsRoute
  '/admin/panels': typeof AdminPanelsRoute
  '/admin/sealed': typeof AdminSealedRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/users': typeof AdminUsersRoute
  '/carta/$slug': typeof CartaSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/orders': typeof OrdersIndexRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-cancel-unpaid': typeof ApiPublicHooksAutoCancelUnpaidRoute
  '/api/public/hooks/price-drop-check': typeof ApiPublicHooksPriceDropCheckRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
  '/api/public/melhorenvio/callback': typeof ApiPublicMelhorenvioCallbackRoute
  '/api/public/payments/mercadopago-webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cartas': typeof CartasRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/conta': typeof ContaRoute
  '/envios': typeof EnviosRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/imas': typeof ImasRoute
  '/orders': typeof OrdersRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/selados': typeof SeladosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/manage-cards': typeof AdminManageCardsRoute
  '/admin/panels': typeof AdminPanelsRoute
  '/admin/sealed': typeof AdminSealedRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/admin/users': typeof AdminUsersRoute
  '/carta/$slug': typeof CartaSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/auto-cancel-unpaid': typeof ApiPublicHooksAutoCancelUnpaidRoute
  '/api/public/hooks/price-drop-check': typeof ApiPublicHooksPriceDropCheckRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
  '/api/public/melhorenvio/callback': typeof ApiPublicMelhorenvioCallbackRoute
  '/api/public/payments/mercadopago-webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cartas'
    | '/checkout'
    | '/conta'
    | '/envios'
    | '/faq'
    | '/favoritos'
    | '/imas'
    | '/orders'
    | '/reset-password'
    | '/selados'
    | '/sitemap.xml'
    | '/sobre'
    | '/unsubscribe'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/integrations'
    | '/admin/manage-cards'
    | '/admin/panels'
    | '/admin/sealed'
    | '/admin/shipping'
    | '/admin/users'
    | '/carta/$slug'
    | '/checkout/return'
    | '/colecao/$slug'
    | '/email/unsubscribe'
    | '/orders/$orderId'
    | '/pay/$orderId'
    | '/orders/'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-cancel-unpaid'
    | '/api/public/hooks/price-drop-check'
    | '/api/public/hooks/update-prices'
    | '/api/public/melhorenvio/callback'
    | '/api/public/payments/mercadopago-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cartas'
    | '/checkout'
    | '/conta'
    | '/envios'
    | '/faq'
    | '/favoritos'
    | '/imas'
    | '/reset-password'
    | '/selados'
    | '/sitemap.xml'
    | '/sobre'
    | '/unsubscribe'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/integrations'
    | '/admin/manage-cards'
    | '/admin/panels'
    | '/admin/sealed'
    | '/admin/shipping'
    | '/admin/users'
    | '/carta/$slug'
    | '/checkout/return'
    | '/colecao/$slug'
    | '/email/unsubscribe'
    | '/orders/$orderId'
    | '/pay/$orderId'
    | '/orders'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-cancel-unpaid'
    | '/api/public/hooks/price-drop-check'
    | '/api/public/hooks/update-prices'
    | '/api/public/melhorenvio/callback'
    | '/api/public/payments/mercadopago-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cartas'
    | '/checkout'
    | '/conta'
    | '/envios'
    | '/faq'
    | '/favoritos'
    | '/imas'
    | '/orders'
    | '/reset-password'
    | '/selados'
    | '/sitemap.xml'
    | '/sobre'
    | '/unsubscribe'
    | '/admin/banners'
    | '/admin/dashboard'
    | '/admin/emails'
    | '/admin/integrations'
    | '/admin/manage-cards'
    | '/admin/panels'
    | '/admin/sealed'
    | '/admin/shipping'
    | '/admin/users'
    | '/carta/$slug'
    | '/checkout/return'
    | '/colecao/$slug'
    | '/email/unsubscribe'
    | '/orders/$orderId'
    | '/pay/$orderId'
    | '/orders/'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/auto-cancel-unpaid'
    | '/api/public/hooks/price-drop-check'
    | '/api/public/hooks/update-prices'
    | '/api/public/melhorenvio/callback'
    | '/api/public/payments/mercadopago-webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartasRoute: typeof CartasRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContaRoute: typeof ContaRoute
  EnviosRoute: typeof EnviosRoute
  FaqRoute: typeof FaqRoute
  FavoritosRoute: typeof FavoritosRoute
  ImasRoute: typeof ImasRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SeladosRoute: typeof SeladosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  CartaSlugRoute: typeof CartaSlugRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAutoCancelUnpaidRoute: typeof ApiPublicHooksAutoCancelUnpaidRoute
  ApiPublicHooksPriceDropCheckRoute: typeof ApiPublicHooksPriceDropCheckRoute
  ApiPublicHooksUpdatePricesRoute: typeof ApiPublicHooksUpdatePricesRoute
  ApiPublicMelhorenvioCallbackRoute: typeof ApiPublicMelhorenvioCallbackRoute
  ApiPublicPaymentsMercadopagoWebhookRoute: typeof ApiPublicPaymentsMercadopagoWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selados': {
      id: '/selados'
      path: '/selados'
      fullPath: '/selados'
      preLoaderRoute: typeof SeladosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imas': {
      id: '/imas'
      path: '/imas'
      fullPath: '/imas'
      preLoaderRoute: typeof ImasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartas': {
      id: '/cartas'
      path: '/cartas'
      fullPath: '/cartas'
      preLoaderRoute: typeof CartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/carta/$slug': {
      id: '/carta/$slug'
      path: '/carta/$slug'
      fullPath: '/carta/$slug'
      preLoaderRoute: typeof CartaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sealed': {
      id: '/admin/sealed'
      path: '/sealed'
      fullPath: '/admin/sealed'
      preLoaderRoute: typeof AdminSealedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/panels': {
      id: '/admin/panels'
      path: '/panels'
      fullPath: '/admin/panels'
      preLoaderRoute: typeof AdminPanelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage-cards': {
      id: '/admin/manage-cards'
      path: '/manage-cards'
      fullPath: '/admin/manage-cards'
      preLoaderRoute: typeof AdminManageCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mercadopago-webhook': {
      id: '/api/public/payments/mercadopago-webhook'
      path: '/api/public/payments/mercadopago-webhook'
      fullPath: '/api/public/payments/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/melhorenvio/callback': {
      id: '/api/public/melhorenvio/callback'
      path: '/api/public/melhorenvio/callback'
      fullPath: '/api/public/melhorenvio/callback'
      preLoaderRoute: typeof ApiPublicMelhorenvioCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/update-prices': {
      id: '/api/public/hooks/update-prices'
      path: '/api/public/hooks/update-prices'
      fullPath: '/api/public/hooks/update-prices'
      preLoaderRoute: typeof ApiPublicHooksUpdatePricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/price-drop-check': {
      id: '/api/public/hooks/price-drop-check'
      path: '/api/public/hooks/price-drop-check'
      fullPath: '/api/public/hooks/price-drop-check'
      preLoaderRoute: typeof ApiPublicHooksPriceDropCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-cancel-unpaid': {
      id: '/api/public/hooks/auto-cancel-unpaid'
      path: '/api/public/hooks/auto-cancel-unpaid'
      fullPath: '/api/public/hooks/auto-cancel-unpaid'
      preLoaderRoute: typeof ApiPublicHooksAutoCancelUnpaidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminManageCardsRoute: typeof AdminManageCardsRoute
  AdminPanelsRoute: typeof AdminPanelsRoute
  AdminSealedRoute: typeof AdminSealedRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminManageCardsRoute: AdminManageCardsRoute,
  AdminPanelsRoute: AdminPanelsRoute,
  AdminSealedRoute: AdminSealedRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartasRoute: CartasRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContaRoute: ContaRoute,
  EnviosRoute: EnviosRoute,
  FaqRoute: FaqRoute,
  FavoritosRoute: FavoritosRoute,
  ImasRoute: ImasRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SeladosRoute: SeladosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  CartaSlugRoute: CartaSlugRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAutoCancelUnpaidRoute: ApiPublicHooksAutoCancelUnpaidRoute,
  ApiPublicHooksPriceDropCheckRoute: ApiPublicHooksPriceDropCheckRoute,
  ApiPublicHooksUpdatePricesRoute: ApiPublicHooksUpdatePricesRoute,
  ApiPublicMelhorenvioCallbackRoute: ApiPublicMelhorenvioCallbackRoute,
  ApiPublicPaymentsMercadopagoWebhookRoute:
    ApiPublicPaymentsMercadopagoWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
