/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecaoSlugRouteImport } from './routes/colecao.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CartaSlugRouteImport } from './routes/carta.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminManageCardsRouteImport } from './routes/admin.manage-cards'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsMercadopagoWebhookRouteImport } from './routes/api/public/payments/mercadopago-webhook'
import { Route as ApiPublicHooksUpdatePricesRouteImport } from './routes/api/public/hooks/update-prices'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoSlugRoute = ColecaoSlugRouteImport.update({
  id: '/colecao/$slug',
  path: '/colecao/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const CartaSlugRoute = CartaSlugRouteImport.update({
  id: '/carta/$slug',
  path: '/carta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManageCardsRoute = AdminManageCardsRouteImport.update({
  id: '/manage-cards',
  path: '/manage-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMercadopagoWebhookRoute =
  ApiPublicPaymentsMercadopagoWebhookRouteImport.update({
    id: '/api/public/payments/mercadopago-webhook',
    path: '/api/public/payments/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUpdatePricesRoute =
  ApiPublicHooksUpdatePricesRouteImport.update({
    id: '/api/public/hooks/update-prices',
    path: '/api/public/hooks/update-prices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/orders': typeof OrdersRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage-cards': typeof AdminManageCardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/carta/$slug': typeof CartaSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
  '/api/public/payments/mercadopago-webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/orders': typeof OrdersRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage-cards': typeof AdminManageCardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/carta/$slug': typeof CartaSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
  '/api/public/payments/mercadopago-webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/orders': typeof OrdersRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/manage-cards': typeof AdminManageCardsRoute
  '/admin/users': typeof AdminUsersRoute
  '/carta/$slug': typeof CartaSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/colecao/$slug': typeof ColecaoSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/hooks/update-prices': typeof ApiPublicHooksUpdatePricesRoute
  '/api/public/payments/mercadopago-webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/favoritos'
    | '/orders'
    | '/admin/banners'
    | '/admin/cards'
    | '/admin/dashboard'
    | '/admin/manage-cards'
    | '/admin/users'
    | '/carta/$slug'
    | '/checkout/return'
    | '/colecao/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/hooks/update-prices'
    | '/api/public/payments/mercadopago-webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/favoritos'
    | '/orders'
    | '/admin/banners'
    | '/admin/cards'
    | '/admin/dashboard'
    | '/admin/manage-cards'
    | '/admin/users'
    | '/carta/$slug'
    | '/checkout/return'
    | '/colecao/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/hooks/update-prices'
    | '/api/public/payments/mercadopago-webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/favoritos'
    | '/orders'
    | '/admin/banners'
    | '/admin/cards'
    | '/admin/dashboard'
    | '/admin/manage-cards'
    | '/admin/users'
    | '/carta/$slug'
    | '/checkout/return'
    | '/colecao/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/hooks/update-prices'
    | '/api/public/payments/mercadopago-webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  OrdersRoute: typeof OrdersRoute
  CartaSlugRoute: typeof CartaSlugRoute
  ColecaoSlugRoute: typeof ColecaoSlugRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicHooksUpdatePricesRoute: typeof ApiPublicHooksUpdatePricesRoute
  ApiPublicPaymentsMercadopagoWebhookRoute: typeof ApiPublicPaymentsMercadopagoWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao/$slug': {
      id: '/colecao/$slug'
      path: '/colecao/$slug'
      fullPath: '/colecao/$slug'
      preLoaderRoute: typeof ColecaoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/carta/$slug': {
      id: '/carta/$slug'
      path: '/carta/$slug'
      fullPath: '/carta/$slug'
      preLoaderRoute: typeof CartaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/manage-cards': {
      id: '/admin/manage-cards'
      path: '/manage-cards'
      fullPath: '/admin/manage-cards'
      preLoaderRoute: typeof AdminManageCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mercadopago-webhook': {
      id: '/api/public/payments/mercadopago-webhook'
      path: '/api/public/payments/mercadopago-webhook'
      fullPath: '/api/public/payments/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/update-prices': {
      id: '/api/public/hooks/update-prices'
      path: '/api/public/hooks/update-prices'
      fullPath: '/api/public/hooks/update-prices'
      preLoaderRoute: typeof ApiPublicHooksUpdatePricesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminManageCardsRoute: typeof AdminManageCardsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminManageCardsRoute: AdminManageCardsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  OrdersRoute: OrdersRoute,
  CartaSlugRoute: CartaSlugRoute,
  ColecaoSlugRoute: ColecaoSlugRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicHooksUpdatePricesRoute: ApiPublicHooksUpdatePricesRoute,
  ApiPublicPaymentsMercadopagoWebhookRoute:
    ApiPublicPaymentsMercadopagoWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
